# Generated by Django 5.0.7 on 2024-07-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBunde', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='app',
            new_name='appBunde',
        ),
    ]
